COMP: Fix windows build error due to missing includes
This commit fixes error like following:

D:\D\S\SSALT-0-build\ShapePopulationViewer\src\ShapePopulationBase.cxx(503):
error C2039: 'back_inserter': is not a member of 'std'