COMP: Ensure sqrt is available in vtkPVPostFilter when built against VTK 9
This commit fixes error like the following reported when building
the project as a Slicer extension:

  /path/to/ShapePopulationViewer/src/vtkPVPostFilter.cxx: In instantiation of ‘void {anonymous}::CopyComponent(T*, T*, int) [with T = vtkArrayIteratorTemplate<char>]’:
  /path/to/ShapePopulationViewer/src/vtkPVPostFilter.cxx:518:5:   required from here
  /path/to/ShapePopulationViewer/src/vtkPVPostFilter.cxx:445:34: error: ‘sqrt’ was not declared in this scope

Co-authored-by: James Fishbaugh <james.fishbaugh@kitware.com>